language: python
python:
- '2.7'
install: true
script:
  - python setup.py install
  - python setup.py test
deploy:
  provider: pypi
  user: azavea
  password:
    secure: t4Cb62B4fvYygunslGzGLRBtVQJD9A8ARUrR/TKK17/xOmR5O4M62mJZfTqSEhhgRNNwMJFVnW0yLEZQxmOYEXkzylqraq9r9qg/974nKe9eqCC/8WlJHNsZO6tECXjZc+HkXpZKptm7YfZSHkBP7wZGU7PJCsWl17KV5XKCW2RDq4dqiDlnVhQadawgr7ZS32x9Xb55Wbc93T5MjWCXNTMjpA5n4DJmtvlUzJZMlyMePgKH8HaKsXv95F2i78cJU46Oahcg+qSchRZGx7/wnSN6Z/U9M/i39J4t5z2lK76esSkK1nBfLP5a/c6rDSABpW0vNWetvohPNcZGsTOZUMbXUbUzjdH9NAby2qTGqk9HWRDK4IZWjcnlZVc+bNvnJSgYLL3c0UzT7DRuT775ckIFGoLGrO7k2nm3cuxmPWMlFk5+b98dNNGDRvCUMx6DXB+2T56Fis1ppg/SE+Gdn6YNgBVkcdXlFp+h0skDziSJpBckr+u8I10BXDb3sqF10cuF5UwIlvEZQGSgu8Rm/FR5+TiGR7Xv00nTlAOq9HWdfJqbUG3pTPzg6hNqxUmduZErD7ktd75Bbpxaa9m8DYbG7UR1u55l2d1fAIChlAseXccERWtTRV7/QQDeeqvwkOXg7kW6EZPTn2ZDK7m2crZ3F0dRu4GAmeTynCKrW9A=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: WikiWatershed/gwlf-e
