name: Release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install pipenv, build dependencies
      run: |
        python -m pip install pipenv
        pipenv install --dev
    - name: Build source package
      run: |
        pipenv run python -m build --sdist
    - name: Build wheels
      run: |
        pipenv run python -m cibuildwheel --output-dir dist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
